# Generated by Axiom (#121) — safe production Vite preset. Do not edit.
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
