# Generated by Axiom (#121) — safe production Node preset. Do not edit.
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN yarn run build

FROM node:20-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY --from=build /app/package.json ./
COPY --from=build /app/yarn.lock ./
RUN yarn install --frozen-lockfile --production
COPY --from=build /app/.next ./.next
USER node
EXPOSE 3000
CMD ["sh", "-c", "yarn start"]
