package traefik

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/digitaleflex/axiom/services/agent/internal/security/ownership"
)

const testDep = "dep_0123456789abcdef01234567"
const testDep2 = "dep_89abcdef0123456789abcdef"

func managedLabels(dep string) map[string]string {
	return map[string]string{
		ownership.LabelManaged:    ownership.ManagedTrue,
		ownership.LabelDeployment: dep,
	}
}

func validRequest() Request {
	return Request{
		Container:    "axiom-app-1",
		Domain:       "app.example.com",
		Port:         3000,
		TLS:          true,
		DeploymentID: testDep,
		ServerID:     "srv_test",
		Labels:       managedLabels(testDep),
	}
}

func TestConfigureGoldenTLS(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{DynamicDir: dir}
	if err := a.Configure(context.Background(), validRequest()); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "axiom-"+testDep+".yml")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# Generated by Axiom; do not edit. Deployment " + testDep + ".\n" +
		"# Static Traefik config (entryPoints web/websecure and the ACME resolver\n" +
		"# named \"le\") is operator-managed and lives outside this file.\n" +
		"http:\n" +
		"  routers:\n" +
		"    axiom-" + testDep + "-web:\n" +
		"      rule: \"Host(`app.example.com`)\"\n" +
		"      entryPoints:\n" +
		"        - web\n" +
		"      middlewares:\n" +
		"        - axiom-" + testDep + "-redirect\n" +
		"      service: axiom-" + testDep + "\n" +
		"    axiom-" + testDep + "-websecure:\n" +
		"      rule: \"Host(`app.example.com`)\"\n" +
		"      entryPoints:\n" +
		"        - websecure\n" +
		"      service: axiom-" + testDep + "\n" +
		"      tls:\n" +
		"        certResolver: le\n" +
		"  middlewares:\n" +
		"    axiom-" + testDep + "-redirect:\n" +
		"      redirectScheme:\n" +
		"        scheme: https\n" +
		"        permanent: true\n" +
		"  services:\n" +
		"    axiom-" + testDep + ":\n" +
		"      loadBalancer:\n" +
		"        servers:\n" +
		"          - url: \"http://axiom-app-1:3000\"\n"
	if string(raw) != want {
		t.Fatalf("golden mismatch:\n--- got ---\n%s\n--- want ---\n%s", raw, want)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o644 {
		t.Fatalf("mode = %v, want 0644", info.Mode().Perm())
	}
}

func TestConfigureNoTLSHasNoRedirectOrCert(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{DynamicDir: dir}
	req := validRequest()
	req.TLS = false
	if err := a.Configure(context.Background(), req); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "axiom-"+testDep+".yml"))
	if err != nil {
		t.Fatal(err)
	}
	// Inspect only the document body (the header comment intentionally
	// documents the operator-managed static config).
	s := string(raw)
	body := s[strings.Index(s, "http:"):]
	if strings.Contains(body, "- websecure") || strings.Contains(body, "certResolver") || strings.Contains(body, "redirectScheme") || strings.Contains(body, "tls:") {
		t.Fatalf("non-TLS config must not emit TLS constructs:\n%s", s)
	}
	if !strings.Contains(s, "axiom-"+testDep+"-web:") || !strings.Contains(s, `url: "http://axiom-app-1:3000"`) {
		t.Fatalf("missing web router or service:\n%s", s)
	}
}

func TestConfigureIdempotent(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{DynamicDir: dir}
	for i := 0; i < 3; i++ {
		if err := a.Configure(context.Background(), validRequest()); err != nil {
			t.Fatalf("configure %d: %v", i, err)
		}
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 || entries[0].Name() != "axiom-"+testDep+".yml" {
		t.Fatalf("entries = %v, want exactly one axiom file", entries)
	}
	// No temp files may be left behind after atomic writes.
	for _, e := range entries {
		if strings.Contains(e.Name(), ".tmp-") {
			t.Fatalf("leftover temp file: %s", e.Name())
		}
	}
}

func TestConfigureInvalidDomainRejected(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{DynamicDir: dir}
	bad := []string{
		"", "App.example.com", "https://app.example.com", "app.example.com:443",
		"app.example.com/path", "app example.com", "-app.example.com",
		"app-.example.com", "app..example.com", "*.example.com", "app_example.com",
	}
	for _, domain := range bad {
		req := validRequest()
		req.Domain = domain
		err := a.Configure(context.Background(), req)
		if !errors.Is(err, ErrInvalidDomain) {
			t.Fatalf("domain %q: err = %v, want ErrInvalidDomain", domain, err)
		}
	}
	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Fatalf("no file may be written for invalid domains: %v", entries)
	}
}

func TestValidDomainAccepts(t *testing.T) {
	good := []string{"app.example.com", "localhost", "a.b.c.example.io", "my-app.example.com", "x1.example.com"}
	for _, d := range good {
		if !ValidDomain(d) {
			t.Fatalf("ValidDomain(%q) = false, want true", d)
		}
	}
}

func TestConfigureInvalidDeploymentAndPort(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{DynamicDir: dir}
	req := validRequest()
	req.DeploymentID = "not-a-deployment"
	if err := a.Configure(context.Background(), req); !errors.Is(err, ErrInvalidDeployment) {
		t.Fatalf("err = %v, want ErrInvalidDeployment", err)
	}
	req = validRequest()
	req.Port = 0
	if err := a.Configure(context.Background(), req); !errors.Is(err, ErrInvalidPort) {
		t.Fatalf("err = %v, want ErrInvalidPort", err)
	}
}

func TestConfigureUnmanagedContainerRefused(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{DynamicDir: dir}
	req := validRequest()
	req.Labels = nil // no ownership labels: fail closed via AssertContainer
	err := a.Configure(context.Background(), req)
	if !errors.Is(err, ErrNotManaged) {
		t.Fatalf("err = %v, want ErrNotManaged", err)
	}
	// Foreign deployment labels are also refused.
	req = validRequest()
	req.Labels = managedLabels(testDep2)
	if err := a.Configure(context.Background(), req); !errors.Is(err, ownership.ErrForeignResource) {
		t.Fatalf("err = %v, want ErrForeignResource", err)
	}
	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Fatalf("no file may be written for foreign containers: %v", entries)
	}
}

func TestConfigureUsesInjectedVerifier(t *testing.T) {
	dir := t.TempDir()
	var gotContainer, gotDep string
	a := &Adapter{
		DynamicDir: dir,
		Verify: ContainerVerifierFunc(func(_ context.Context, container, deploymentID string) error {
			gotContainer, gotDep = container, deploymentID
			return nil
		}),
	}
	req := validRequest()
	req.Labels = nil
	if err := a.Configure(context.Background(), req); err != nil {
		t.Fatal(err)
	}
	if gotContainer != "axiom-app-1" || gotDep != testDep {
		t.Fatalf("verifier got (%q, %q)", gotContainer, gotDep)
	}
}

func TestConfigureAtomicOnMarshalError(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{
		DynamicDir: dir,
		Marshal: func(Request) ([]byte, error) {
			return nil, errors.New("boom")
		},
	}
	if err := a.Configure(context.Background(), validRequest()); err == nil {
		t.Fatal("expected marshal error")
	}
	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Fatalf("marshal failure must leave no partial file: %v", entries)
	}
}

func TestReconcileRemovesOnlyStaleAxiomFiles(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{DynamicDir: dir}
	// Two Axiom-owned configs, one active one stale.
	if err := a.Configure(context.Background(), validRequest()); err != nil {
		t.Fatal(err)
	}
	stale := validRequest()
	stale.DeploymentID = testDep2
	stale.Labels = managedLabels(testDep2)
	if err := a.Configure(context.Background(), stale); err != nil {
		t.Fatal(err)
	}
	// Foreign files that must never be touched.
	foreign := map[string]string{
		"traefik.yml":                    "entryPoints: {}\n",
		"other-dep_0123456789abcdef.yml": "x: 1\n",
		"axiom-not-a-deployment.yml":     "y: 2\n", // axiom prefix, unparseable id
		"readme.txt":                     "hello\n",
	}
	for name, body := range foreign {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	removed, err := a.Reconcile([]string{testDep})
	if err != nil {
		t.Fatal(err)
	}
	if len(removed) != 1 || removed[0] != "axiom-"+testDep2+".yml" {
		t.Fatalf("removed = %v, want [axiom-%s.yml]", removed, testDep2)
	}
	if _, err := os.Stat(filepath.Join(dir, "axiom-"+testDep+".yml")); err != nil {
		t.Fatalf("active config must be kept: %v", err)
	}
	for name := range foreign {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Fatalf("foreign file %q must be kept: %v", name, err)
		}
	}
}

func TestReconcileMissingDirIsNoop(t *testing.T) {
	a := &Adapter{DynamicDir: filepath.Join(t.TempDir(), "does-not-exist")}
	removed, err := a.Reconcile([]string{testDep})
	if err != nil {
		t.Fatalf("err = %v, want nil", err)
	}
	if len(removed) != 0 {
		t.Fatalf("removed = %v, want none", removed)
	}
}

func TestRemoveIdempotent(t *testing.T) {
	dir := t.TempDir()
	a := &Adapter{DynamicDir: dir}
	if err := a.Configure(context.Background(), validRequest()); err != nil {
		t.Fatal(err)
	}
	if err := a.Remove(testDep); err != nil {
		t.Fatal(err)
	}
	if err := a.Remove(testDep); err != nil {
		t.Fatalf("second remove must be a no-op: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "axiom-"+testDep+".yml")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("file still present: %v", err)
	}
	if err := a.Remove("bad"); !errors.Is(err, ErrInvalidDeployment) {
		t.Fatalf("err = %v, want ErrInvalidDeployment", err)
	}
}

func TestConfigureNoDynamicDir(t *testing.T) {
	a := &Adapter{}
	if err := a.Configure(context.Background(), validRequest()); !errors.Is(err, ErrNoDynamicDir) {
		t.Fatalf("err = %v, want ErrNoDynamicDir", err)
	}
}
