// Package agentkey owns the per-agent Engine→Agent operation signing key
// (ADR-0008) and the signing primitives of the Engine→Agent leg.
//
// The key is generated by the Engine (32 bytes, crypto/rand), stored encrypted
// at rest (AES-256-GCM, internal/security/secrets) under the scope
// agent:<agentId> / name "operation-signing-key", and returned in clear
// exactly once — at registration and at every rotation, in the
// "operationSigningKey" field (lowercase hex) of the register/rotate response.
// It never travels again: rotation reissues it the same way agentauth
// reissues a credential.
//
// Every dispatched operation is signed with HMAC-SHA256 over a canonical form
// of the request. The wire contract is fixed and byte-exact with the agent
// side (services/agent/internal/security/operationkey):
//
//	canonical = strings.Join([]string{
//		"AXIOM-HMAC-V1",   // domain separator
//		"<METHOD>",        // POST
//		"<PATH>",          // request path, e.g. /api/v1/agent/operations
//		"<AgentID>",       // the target agent's ID, known independently of the body
//		"<Version>",       // numeric protocol version of the operation (2)
//		"<Timestamp>",     // exact X-Timestamp value
//		"<Nonce>",         // exact X-Nonce value
//		"<sha256(body)>",  // lowercase hex over the raw body bytes
//	}, "\n")             // no trailing newline
//
// signature = hex-lowercase HMAC-SHA256(canonical, key), sent as
// "X-Axiom-Signature: v1=<hex-lowercase>" and compared with hmac.Equal.
//
// SECURITY: the key is plaintext only inside this process, for signing. It is
// never logged, never included in errors, never returned by a metadata API and
// never presented as a bearer credential — it cannot authenticate to the
// Engine. Storing it reversibly is a deliberate, documented exception to the
// hash-only rule of agentauth (ADR-0008): signing requires a key.
package agentkey

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/digitaleflex/axiom/services/engine/internal/security/secrets"
)

// Wire headers and canonical-form constants. These are part of the wire
// contract: the Engine signs with exactly these names and values.
const (
	// SignatureHeader carries the operation signature.
	SignatureHeader = "X-Axiom-Signature"
	// SignaturePrefix versions the signature scheme; the value that follows
	// is the lowercase hex HMAC-SHA256.
	SignaturePrefix = "v1="
	// TimestampHeader carries the signing timestamp (RFC3339).
	TimestampHeader = "X-Timestamp"
	// NonceHeader carries a per-request nonce (anti-replay).
	NonceHeader = "X-Nonce"
	// CanonicalDomain is the first canonical line: a domain separator that
	// keeps operation signatures from ever colliding with another HMAC.
	CanonicalDomain = "AXIOM-HMAC-V1"
	// KeySize is the size in bytes of a key on the wire (64 hex characters).
	KeySize = 32
)

// Secret-store placement of one agent's key, mirroring the appconfig scope
// prefix convention (internal/secrets/appconfig.go).
const (
	// ScopePrefix namespaces every agent's secrets in the store.
	ScopePrefix = "agent:"
	// KeyName is the single secret name held under an agent's scope.
	KeyName = "operation-signing-key"
)

// Errors.
var (
	// ErrNoKey means no operation signing key is stored for this agent: the
	// Engine cannot sign an operation towards it and must fail closed rather
	// than dispatch unsigned work.
	ErrNoKey = errors.New("agentkey: no operation signing key for this agent")
	// ErrInvalidKey means the key material is malformed and must never be
	// used to sign.
	ErrInvalidKey = errors.New("agentkey: invalid operation signing key")
)

// Key is a raw HMAC-SHA256 operation signing key. Production keys are exactly
// KeySize bytes (the wire field is lowercase hex); the type itself carries the
// raw bytes so the signing primitives are usable with any key length.
type Key []byte

// Sign returns the lowercase hex HMAC-SHA256 of canonical under k. It is the
// value that follows "v1=" in the signature header.
func (k Key) Sign(canonical string) string {
	mac := hmac.New(sha256.New, []byte(k))
	mac.Write([]byte(canonical))
	return hex.EncodeToString(mac.Sum(nil))
}

// Hex returns the lowercase hex encoding of the key (the wire form, used by
// the "operationSigningKey" field of the register/rotate response).
func (k Key) Hex() string { return hex.EncodeToString(k) }

// BodyDigest returns the lowercase hex SHA-256 of body: the eighth canonical
// line, computed over the raw bytes as sent.
func BodyDigest(body []byte) string {
	sum := sha256.Sum256(body)
	return hex.EncodeToString(sum[:])
}

// Canonical builds the exact signed form (see the package doc). The lines are
// joined with "\n" and there is NO trailing newline; timestamp and nonce are
// the exact header values, never a normalized copy.
func Canonical(method, path, agentID string, version int, timestamp, nonce string, body []byte) string {
	return strings.Join([]string{
		CanonicalDomain,
		method,
		path,
		agentID,
		strconv.Itoa(version),
		timestamp,
		nonce,
		BodyDigest(body),
	}, "\n")
}

// Service stores and resolves per-agent operation signing keys in the Engine's
// encrypted secret store (security/secrets.EncryptedStore), the same store
// appconfig uses. Keys are write-once-per-rotation: the store holds only the
// sealed form and SigningKey decrypts it for the signer alone.
type Service struct {
	Store *secrets.EncryptedStore
}

// scopeFor returns the store scope of one agent.
func scopeFor(agentID string) string { return ScopePrefix + agentID }

// Issue generates a fresh KeySize-byte operation signing key for agentID and
// stores it sealed under scope agent:<agentId>/operation-signing-key. The
// plaintext key is returned exactly once: callers hand it to the agent at
// registration or rotation and never log, persist or expose it again.
//
// Issue is also the rotation primitive: every call replaces the stored key,
// exactly the way agentauth reissues a credential on rotate.
func (s *Service) Issue(ctx context.Context, agentID string) (Key, error) {
	if s == nil || s.Store == nil {
		return nil, errors.New("agentkey: secret store is required")
	}
	if strings.TrimSpace(agentID) == "" {
		return nil, errors.New("agentkey: agent id is required")
	}
	key := make([]byte, KeySize)
	if _, err := rand.Read(key); err != nil {
		return nil, fmt.Errorf("agentkey: generate key: %w", err)
	}
	// Stored as lowercase hex (the wire form): the sealed blob then contains
	// text-safe material and the round trip proves the length.
	if err := s.Store.Put(ctx, scopeFor(agentID), KeyName, hex.EncodeToString(key)); err != nil {
		return nil, err
	}
	return Key(key), nil
}

// SigningKey decrypts the current operation signing key of agentID.
//
// SECURITY: plaintext is returned to the signer only — it is never logged,
// never sent over the wire again and never included in errors. An agent with
// no stored key yields ErrNoKey and the caller must refuse the operation.
func (s *Service) SigningKey(ctx context.Context, agentID string) (Key, error) {
	if s == nil || s.Store == nil {
		return nil, errors.New("agentkey: secret store is required")
	}
	if strings.TrimSpace(agentID) == "" {
		return nil, errors.New("agentkey: agent id is required")
	}
	stored, err := s.Store.Get(ctx, scopeFor(agentID), KeyName)
	if errors.Is(err, secrets.ErrNotFound) {
		return nil, ErrNoKey
	}
	if err != nil {
		return nil, err
	}
	key, err := hex.DecodeString(stored)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidKey, err)
	}
	if len(key) != KeySize {
		return nil, fmt.Errorf("%w: %d bytes, want %d", ErrInvalidKey, len(key), KeySize)
	}
	return Key(key), nil
}
