package node

import (
	"fmt"
	"strings"

	"github.com/digitaleflex/axiom/services/engine/internal/runtime/presets"
)

// DockerfileForFacts renders the safe multi-stage Dockerfile for the facts.
// The template is fully determined by the facts: the same facts always
// produce the same Dockerfile.
func DockerfileForFacts(f Facts) (string, error) {
	p, err := Resolve(f)
	if err != nil {
		return "", err
	}
	if f.Framework == presets.FrameworkVite {
		return viteDockerfile(f, p), nil
	}
	return nodeDockerfile(f, p), nil
}

// depsInstall installs all dependencies (including dev) in the deps stage.
// The lockfile-aware commands keep builds reproducible.
func depsInstall(pm string, hasLockfile bool) string {
	switch pm {
	case presets.PackageManagerNPM:
		if hasLockfile {
			return "npm ci"
		}
		return "npm install"
	case presets.PackageManagerPNPM:
		if hasLockfile {
			return "pnpm fetch"
		}
		return "pnpm install"
	case presets.PackageManagerYarn, presets.PackageManagerBun:
		return pm + " install"
	default:
		return "npm ci"
	}
}

// prodInstall installs production-only dependencies in the runtime stage.
func prodInstall(pm string, hasLockfile bool) string {
	switch pm {
	case presets.PackageManagerNPM:
		if hasLockfile {
			return "npm ci --omit=dev"
		}
		return "npm install --omit=dev"
	case presets.PackageManagerPNPM:
		if hasLockfile {
			return "pnpm install --frozen-lockfile --prod"
		}
		return "pnpm install --prod"
	case presets.PackageManagerYarn:
		if hasLockfile {
			return "yarn install --frozen-lockfile --production"
		}
		return "yarn install --production"
	default: // bun
		if hasLockfile {
			return "bun install --frozen-lockfile --production"
		}
		return "bun install --production"
	}
}

// lockfileName is the canonical lockfile of each package manager.
func lockfileName(pm string) string {
	switch pm {
	case presets.PackageManagerNPM:
		return "package-lock.json"
	case presets.PackageManagerPNPM:
		return "pnpm-lock.yaml"
	case presets.PackageManagerYarn:
		return "yarn.lock"
	default: // bun
		return "bun.lockb"
	}
}

// nodeDockerfile renders the multi-stage Dockerfile for Next.js and generic
// Node.js applications: deps → build → minimal runtime.
func nodeDockerfile(f Facts, p NodePreset) string {
	var b strings.Builder
	b.WriteString("# Generated by Axiom (#121) — safe production Node preset. Do not edit.\n")
	fmt.Fprintf(&b, "FROM %s AS deps\n", Node20Alpine)
	b.WriteString("WORKDIR /app\n")
	writeManifestCopy(&b, f, p.PackageManager)
	fmt.Fprintf(&b, "RUN %s\n", depsInstall(p.PackageManager, f.HasLockfile))

	fmt.Fprintf(&b, "\nFROM %s AS build\n", Node20Alpine)
	b.WriteString("WORKDIR /app\n")
	b.WriteString("COPY --from=deps /app/node_modules ./node_modules\n")
	b.WriteString("COPY . .\n")
	if p.BuildCommand != "" {
		fmt.Fprintf(&b, "RUN %s\n", p.BuildCommand)
	}

	fmt.Fprintf(&b, "\nFROM %s\n", Node20Alpine)
	b.WriteString("ENV NODE_ENV=production\n")
	b.WriteString("WORKDIR /app\n")
	if p.OutputDir != "" {
		// Minimal runtime: manifest, lockfile, build output, prod dependencies.
		b.WriteString("COPY --from=build /app/package.json ./\n")
		if f.HasLockfile {
			fmt.Fprintf(&b, "COPY --from=build /app/%s ./\n", lockfileName(p.PackageManager))
		}
		fmt.Fprintf(&b, "RUN %s\n", prodInstall(p.PackageManager, f.HasLockfile))
		fmt.Fprintf(&b, "COPY --from=build /app/%s ./%s\n", p.OutputDir, p.OutputDir)
	} else {
		// Generic Node: the whole application, dependencies pruned to production.
		b.WriteString("COPY --from=build /app ./\n")
		fmt.Fprintf(&b, "RUN %s\n", prodInstall(p.PackageManager, f.HasLockfile))
	}
	b.WriteString("USER node\n")
	fmt.Fprintf(&b, "EXPOSE %d\n", p.Port)
	fmt.Fprintf(&b, "CMD [\"sh\", \"-c\", %s]\n", shellQuote(p.StartCommand))
	return b.String()
}

// viteDockerfile renders the multi-stage Dockerfile for Vite applications:
// deps → build → static output served by nginx.
func viteDockerfile(f Facts, p NodePreset) string {
	var b strings.Builder
	b.WriteString("# Generated by Axiom (#121) — safe production Vite preset. Do not edit.\n")
	fmt.Fprintf(&b, "FROM %s AS deps\n", Node20Alpine)
	b.WriteString("WORKDIR /app\n")
	writeManifestCopy(&b, f, p.PackageManager)
	fmt.Fprintf(&b, "RUN %s\n", depsInstall(p.PackageManager, f.HasLockfile))

	fmt.Fprintf(&b, "\nFROM %s AS build\n", Node20Alpine)
	b.WriteString("WORKDIR /app\n")
	b.WriteString("COPY --from=deps /app/node_modules ./node_modules\n")
	b.WriteString("COPY . .\n")
	if p.BuildCommand != "" {
		fmt.Fprintf(&b, "RUN %s\n", p.BuildCommand)
	}

	// Static output: nginx serves the build. The nginx master process needs
	// root to start and drops to the nginx worker user; there is no
	// HEALTHCHECK because minimal images ship without curl/wget — Axiom
	// probes health externally.
	fmt.Fprintf(&b, "\nFROM %s\n", NginxAlpine)
	fmt.Fprintf(&b, "COPY --from=build /app/%s /usr/share/nginx/html\n", p.OutputDir)
	b.WriteString("EXPOSE 80\n")
	return b.String()
}

// writeManifestCopy copies package.json and, when present, the lockfile.
func writeManifestCopy(b *strings.Builder, f Facts, pm string) {
	if f.HasLockfile {
		fmt.Fprintf(b, "COPY package.json %s ./\n", lockfileName(pm))
	} else {
		b.WriteString("COPY package.json ./\n")
	}
}

func shellQuote(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}
